/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/jacky/grpcui/sidecar/ffi */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 5 "bridge.go"

#include <stdlib.h>
#include <string.h>

// Buffer represents a byte buffer returned to C
typedef struct {
    char* data;
    size_t len;
} Buffer;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// bridge_new creates a new bridge handle
//
extern uintptr_t bridge_new(void);

// bridge_free frees a bridge handle
//
extern void bridge_free(uintptr_t handle);

// reset_parser 重置桥接实例的运行态缓存与连接。
//
// 该接口供上层在“切换项目/断开连接”时显式调用，保证下一次加载 proto 前
// 后端状态完全干净，不会混入上一个项目的服务描述。
//
extern int reset_parser(uintptr_t handle);

// load_proto_files loads proto files from disk
//
extern int load_proto_files(uintptr_t handle, char* protoPathsJSON, char* importPathsJSON);

// load_reflection loads proto definitions via server reflection
//
extern int load_reflection(uintptr_t handle, char* targetAddr, char* tlsConfigJSON);

// list_services returns a JSON array of all services
//
extern char* list_services(uintptr_t handle);

// list_methods returns a JSON array of methods for a service
//
extern char* list_methods(uintptr_t handle, char* serviceName);

// get_method_input_schema returns request message schema for a method.
//
extern char* get_method_input_schema(uintptr_t handle, char* serviceName, char* methodName);

// encode_request_json_to_wire encodes JSON payload to wire format
//
extern Buffer* encode_request_json_to_wire(uintptr_t handle, char* methodName, char* jsonPayload);

// decode_response_wire_to_json decodes wire format bytes to JSON
//
extern char* decode_response_wire_to_json(uintptr_t handle, char* methodName, char* wireData, size_t wireLen);

// last_error returns the last error message
//
extern char* last_error(void);

// free_buffer frees a buffer allocated by Go
//
extern void free_buffer(void* buf);

// free_cstring frees a C string allocated by Go
//
extern void free_cstring(char* s);

#ifdef __cplusplus
}
#endif
